// src/ai/engine/pptEngine.js
// Enterprise PPT slide deck engine — produces structured 2-column executive slide data
// and generates authentic Microsoft PowerPoint (.pptx) presentations via pptxgenjs.

import pptxgen from 'pptxgenjs';
import { generateExecutiveBrief } from './executiveBriefEngine.js';
import { detectAllAnomalies } from './anomalyEngine.js';
import { getSalesLargeDeals } from '../tools/salesTools.js';
import { getRiskSummary } from '../tools/crossModuleTools.js';

function fmtCr(n) {
  if (n == null) return 'N/A';
  if (Math.abs(n) >= 1000) return `₹${(n / 1000).toFixed(1)}K Cr`;
  return `₹${n.toFixed(1)} Cr`;
}
function fmt1(n) {
  return n != null ? n.toFixed(1) : 'N/A';
}

export function generatePPTContent(filters = {}) {
  try {
    const brief     = generateExecutiveBrief(filters);
    const anomalies = detectAllAnomalies(filters);
    const risks     = getRiskSummary(filters);

    let topDeals = [];
    try {
      const deals = getSalesLargeDeals(filters);
      topDeals = deals.slice(0, 3);
    } catch (_) {}

    const slides = [
      // ─── Slide 1: Executive Summary & Corporate Health ─────────────────────
      {
        id:       1,
        title:    'Executive Summary & Corporate Health',
        subtitle: `Cross-Functional Executive Briefing · ${brief?.generatedAt || new Date().toLocaleDateString()}`,
        type:     'executive',
        kpis: brief ? [
          { label: 'Revenue',         value: brief.revenue.achievementLabel, sub: `${fmt1(brief.revenue.achievement)}% of AOP`, sentiment: brief.revenue.sentiment },
          { label: 'YoY Growth',      value: `${brief.revenue.yoyGrowth >= 0 ? '+' : ''}${fmt1(brief.revenue.yoyGrowth)}%`, sub: 'YoY Trajectory', sentiment: brief.revenue.yoyGrowth >= 0 ? 'positive' : 'negative' },
          { label: 'Gross Margin',    value: `${fmt1(brief.finance.grossMargin)}%`, sub: brief.finance.status, sentiment: brief.finance.sentiment },
          { label: 'Sales TCV',       value: `${fmt1(brief.sales.achievement)}%`, sub: 'AOP Target', sentiment: brief.sales.sentiment },
          { label: 'Customer CSI',    value: `${fmt1(brief.deg.csiScore)}%`, sub: brief.deg.status, sentiment: brief.deg.sentiment },
          { label: 'Client Meetings', value: brief.account.status, sub: brief.account.direction, sentiment: brief.account.sentiment },
        ] : [],
        leftSection: {
          title: 'Executive Highlights & Business Drivers',
          items: brief ? [
            `**Revenue Attainment:** Portfolio delivery tracking at **${fmt1(brief.revenue.achievement)}% of AOP** (${brief.revenue.status}).`,
            `**Margin Realization:** Gross margin remains steady at **${fmt1(brief.finance.grossMargin)}%** supported by offshore billability.`,
            `**Commercial Pipeline:** Active sales pipeline is **${brief.sales.pipelineStatus}** with a **${brief.sales.outlook}** outlook.`,
            `**Delivery Quality:** Customer satisfaction index at **${fmt1(brief.deg.csiScore)}%**, indicating stable engagement health.`,
          ] : ['No executive data available for the current filter context.'],
        },
        rightSection: {
          title: 'Strategic Priorities & Immediate Focus',
          items: brief ? [
            `**Regional Intervention:** Close operational gaps in underperforming markets with dedicated leadership focus.`,
            `**Cost Discipline:** Maintain tight controls on subcontractor ramp-ups and third-party bought-out services.`,
            `**Pipeline Acceleration:** Prioritize late-stage qualified opportunities to safeguard upcoming quarterly targets.`,
            `**Client Expansion:** Leverage rising executive meeting momentum for strategic multi-year extensions.`,
          ] : ['No focus items available.'],
        },
        bullets: brief ? [
          `Revenue: ${brief.revenue.achievementLabel} at ${fmt1(brief.revenue.achievement)}% of AOP — ${brief.revenue.status}`,
          `Gross margin at ${fmt1(brief.finance.grossMargin)}% — ${brief.finance.status}`,
          `Sales pipeline is ${brief.sales.pipelineStatus} — outlook ${brief.sales.outlook}`,
          `Customer satisfaction (CSI) at ${fmt1(brief.deg.csiScore)}% — ${brief.deg.status}`,
        ] : [],
        note: 'Executive intelligence summary generated by Crystal Ball AI Analytics Engine.',
      },

      // ─── Slide 2: Revenue Performance & Regional Analysis ──────────────────
      {
        id:       2,
        title:    'Revenue Performance & Regional Analysis',
        subtitle: 'AOP Budget Variance, Regional Dynamics & Growth Breakdown',
        type:     'revenue',
        kpis: brief ? [
          { label: 'Actual Revenue', value: brief.revenue.achievementLabel, sub: 'YTD Delivery', sentiment: 'neutral' },
          { label: 'AOP Target',     value: brief.revenue.aop, sub: 'Annual Plan', sentiment: 'neutral' },
          { label: 'AOP Achieved',   value: `${fmt1(brief.revenue.achievement)}%`, sub: brief.revenue.status, sentiment: brief.revenue.sentiment },
          { label: 'YoY Growth',     value: `${brief.revenue.yoyGrowth >= 0 ? '+' : ''}${fmt1(brief.revenue.yoyGrowth)}%`, sub: 'Year-over-Year', sentiment: brief.revenue.yoyGrowth >= 0 ? 'positive' : 'negative' },
        ] : [],
        leftSection: {
          title: 'Geographic Performance Analysis',
          items: brief ? [
            `**Leading Market:** **${brief.topGeo}** leads the portfolio with consistent delivery above target expectations.`,
            `**Underperforming Market:** **${brief.worstGeo}** lags target and represents the main regional gap to planned AOP.`,
            `**Growth Trajectory:** Revenue trend is **${brief.revenue.yoyGrowth >= 0 ? 'growing' : 'contracting'} at ${fmt1(Math.abs(brief.revenue.yoyGrowth || 0))}% YoY**.`,
            `**Target Variance:** Focused account intervention is required to recover regional run-rates.`,
          ] : ['No regional data available.'],
        },
        rightSection: {
          title: 'Growth Levers & Gap Closure Plan',
          items: brief ? [
            `**Regional Turnaround:** Deploy specialized delivery taskforces to lagging accounts in ${brief.worstGeo}.`,
            `**Rate Card Protection:** Maintain strict pricing governance across both onsite and offshore engagements.`,
            `**Cluster Cross-Sell:** Accelerate technology and cloud service penetration into established customer bases.`,
            `**Full-Year Outlook:** Sustaining top cluster momentum ensures reliable path toward fiscal year milestones.`,
          ] : ['No recovery actions available.'],
        },
        bullets: brief ? [
          `Top performing geography: ${brief.topGeo}`,
          `Geography needing attention: ${brief.worstGeo}`,
          `Revenue growth: ${brief.revenue.yoyGrowth >= 0 ? '+' : ''}${fmt1(brief.revenue.yoyGrowth)}% YoY`,
        ] : [],
        note: 'Source: Revenue Performance Module · Crystal Ball Analytics',
      },

      // ─── Slide 3: Enterprise Risk & Anomaly Watchtower ─────────────────────
      {
        id:       3,
        title:    'Enterprise Risk & Anomaly Watchtower',
        subtitle: `${anomalies.length} statistically significant variances detected across ${[...new Set(anomalies.map(a => a.module))].length} modules`,
        type:     'risks',
        kpis: [
          { label: 'Total Anomalies', value: `${anomalies.length}`, sub: 'Detected Issues', sentiment: anomalies.length === 0 ? 'positive' : 'negative' },
          { label: 'Critical Level',  value: `${anomalies.filter(a => a.severity === 'critical').length}`, sub: 'Immediate Action', sentiment: anomalies.filter(a => a.severity === 'critical').length === 0 ? 'positive' : 'negative' },
          { label: 'High Priority',   value: `${anomalies.filter(a => a.severity === 'high').length}`, sub: 'Watchlist Items', sentiment: 'neutral' },
          { label: 'Engine Status',   value: 'Active', sub: 'Statistical Guardrails', sentiment: 'positive' },
        ],
        leftSection: {
          title: 'Top Detected Variances Across Modules',
          items: risks.length > 0
            ? risks.slice(0, 4).map(r => `**${r.title}:** ${r.detail}`)
            : ['No statistical anomalies detected in the current data scope.'],
        },
        rightSection: {
          title: 'Governance Protocols & Risk Containment',
          items: [
            `**Executive Escalations:** Institute bi-weekly operational check-ins for clusters with margin decline > 1.5pp.`,
            `**Commercial Governance:** Perform deep-dive risk reviews on qualified pursuits experiencing stage delays.`,
            `**Talent Reallocation:** Coordinate with RMG to shift available bench personnel to high-margin demand pools.`,
            `**Automated Guardrails:** Continuous statistical monitoring provides proactive warning before threshold breach.`,
          ],
        },
        bullets: risks.slice(0, 5).map(r => `${r.title} — ${r.detail}`),
        note: 'Statistical anomaly detection executed on real-time enterprise dataset.',
      },

      // ─── Slide 4: Sales Pipeline & Commercial Outlook ──────────────────────
      {
        id:       4,
        title:    'Sales Pipeline & Commercial Outlook',
        subtitle: 'TCV Performance, Deal Velocity & High-Value Opportunity Review',
        type:     'sales',
        kpis: brief ? [
          { label: 'TCV Attainment',  value: `${fmt1(brief.sales.achievement)}%`, sub: 'AOP Target', sentiment: brief.sales.sentiment },
          { label: 'Pipeline Trend',  value: brief.sales.pipelineStatus, sub: 'Qualified Coverage', sentiment: brief.sales.pipelineStatus === 'increasing' ? 'positive' : 'negative' },
          { label: 'Commercial Bias', value: brief.sales.outlook, sub: 'Conversion Outlook', sentiment: brief.sales.outlook === 'Positive' ? 'positive' : 'neutral' },
          { label: 'Top Pursuits',    value: `${topDeals.length} Deals`, sub: 'Late Evaluation Stage', sentiment: 'positive' },
        ] : [],
        leftSection: {
          title: 'Pipeline Health & Velocity',
          items: brief ? [
            `**TCV Target Attainment:** Won deals currently stand at **${fmt1(brief.sales.achievement)}%** of the annual plan.`,
            `**Coverage Trajectory:** Total qualified opportunities display a **${brief.sales.pipelineStatus}** quarter-over-quarter trend.`,
            `**Stage Concentration:** Healthy pipeline density in active negotiation and proposal stages.`,
            `**Win Velocity:** Core competitive pursuits are closing within established commercial cycles.`,
          ] : ['No sales pipeline data available.'],
        },
        rightSection: {
          title: 'Key Strategic Pursuits Under Review',
          items: topDeals.length > 0 ? [
            ...topDeals.slice(0, 3).map(d => `**${d.opportunityName?.slice(0, 32)}:** $${d.tcv?.toFixed(0)}M deal targeting near-term contract execution.`),
            `**Executive Engagement:** Align C-level sponsors to support final negotiation closures.`,
          ] : [
            `**Deal Acceleration:** Review stage 3+ opportunities with cluster leaders.`,
            `**Renewal Protection:** Safeguard high-value recurring revenue engagements.`,
          ],
        },
        bullets: [
          brief ? `Sales TCV achievement at ${fmt1(brief.sales.achievement)}% — ${brief.sales.status}` : '',
          ...topDeals.slice(0, 3).map(d => `Deal: ${d.opportunityName} ($${d.tcv?.toFixed(0)}M)`),
        ].filter(Boolean),
        note: 'Source: Sales Performance Module · Crystal Ball Analytics',
      },

      // ─── Slide 5: Executive Action Plan & Roadmap ──────────────────────────
      {
        id:       5,
        title:    'Executive Action Plan & Governance Roadmap',
        subtitle: 'AI-Synthesized Management Priorities & Implementation Cadence',
        type:     'actions',
        kpis: [
          { label: 'Strategic Pillars', value: '3 Priorities', sub: 'Action Roadmap', sentiment: 'positive' },
          { label: 'Delivery Quality',   value: brief ? `${fmt1(brief.deg.csiScore)}%` : 'Stable', sub: 'CSI Satisfaction', sentiment: 'positive' },
          { label: 'Client Engagement',  value: brief ? brief.account.direction : 'Growing', sub: 'Executive Visits', sentiment: 'positive' },
          { label: 'Execution Horizon',  value: 'Active Q4', sub: 'Near-Term Focus', sentiment: 'neutral' },
        ],
        leftSection: {
          title: 'Top Executive Management Priorities',
          items: brief && brief.focusAreas ? [
            ...brief.focusAreas.slice(0, 3).map((f, i) => `**Priority ${i + 1}:** ${f}`),
            `**Delivery Rigor:** Maintain operational standards to protect customer satisfaction index.`,
          ] : ['No strategic priorities available.'],
        },
        rightSection: {
          title: 'Governance & Review Cadence',
          items: [
            `**Executive Sponsor Visits:** Align leadership visits with accounts displaying positive engagement momentum.`,
            `**Talent & Cost Synchronization:** Partner RMG bench fulfillment directly with margin-accretive cluster demand.`,
            `**Weekly Metric Reviews:** Monitor module KPIs, margin trends, and anomaly indicators on the AI Hub.`,
            `**Board Reporting:** Package monthly Crystal Ball AI executive briefing for senior governance reviews.`,
          ],
        },
        bullets: brief && brief.focusAreas ? brief.focusAreas : ['No action plan available.'],
        note: 'AI-generated management action plan. Validate with business leadership.',
        isActionSlide: true,
      },
    ];

    return {
      slides,
      brief,
      generatedAt: brief?.generatedAt || new Date().toLocaleDateString(),
      totalAnomalies: anomalies.length,
      mode: 'ENTERPRISE_AI',
    };
  } catch (e) {
    console.error('[PPTEngine] Error:', e);
    return null;
  }
}

/**
 * Generates an authentic Microsoft PowerPoint (.pptx) presentation file
 * and triggers direct browser download.
 *
 * Designed with 16:9 widescreen layout, McKinsey/Gartner style executive card layout:
 * - Navy / Sapphire executive header banner with title, subtitle, and badge
 * - 4 to 6 evenly spaced KPI stat cards with labels, main numbers, subtext, and sentiment colors
 * - 2-Column structured container cards with headers and indented bullet points
 * - Governance footer line with confidentiality notice, timestamp, and slide number
 */
export async function exportToPPTX(filters = {}) {
  const pptData = generatePPTContent(filters);
  if (!pptData || !pptData.slides) throw new Error('Failed to generate slide content');

  const pptx = new pptxgen();
  // Set true 16:9 widescreen layout (13.33 inches wide by 7.5 inches high)
  pptx.layout = 'LAYOUT_WIDE';
  pptx.author = 'Crystal Ball Enterprise Analytics AI';
  pptx.company = 'Crystal Ball Analytics';
  pptx.title = 'Executive Briefing & Performance Analytics';

  for (const s of pptData.slides) {
    const slide = pptx.addSlide();
    slide.background = { color: 'F8FAFC' };

    // ─── 1. Header Banner (y: 0 to 1.05) ──────────────────────────────────
    const headerColor =
      s.type === 'risks'   ? '7F1D1D' :
      s.type === 'actions' ? '064E3B' :
      s.type === 'sales'   ? '4C1D95' : '1E3A5F';

    slide.addShape(pptx.ShapeType.rect, {
      x: 0, y: 0, w: '100%', h: 1.05,
      fill: { color: headerColor }
    });

    // Brand tag / tracker
    slide.addText(`SLIDE ${s.id} OF 5 · CRYSTAL BALL ENTERPRISE AI`, {
      x: 0.5, y: 0.12, w: 8.0, h: 0.20,
      fontSize: 8.5, color: '93C5FD', bold: true, fontFace: 'Calibri'
    });

    // Slide Title
    slide.addText(s.title, {
      x: 0.5, y: 0.32, w: 9.5, h: 0.38,
      fontSize: 19, color: 'FFFFFF', bold: true, fontFace: 'Calibri'
    });

    // Subtitle
    slide.addText(s.subtitle || '', {
      x: 0.5, y: 0.72, w: 9.5, h: 0.24,
      fontSize: 10, color: 'E2E8F0', fontFace: 'Calibri'
    });

    // Top Right Logo / Badge
    slide.addText('EXECUTIVE BRIEFING', {
      x: 10.2, y: 0.35, w: 2.6, h: 0.30,
      fontSize: 8.5, color: 'FFFFFF', bold: true, align: 'right', fontFace: 'Calibri'
    });

    // ─── 2. KPI Stat Cards Row (y: 1.18 to 1.93) ──────────────────────────
    if (s.kpis && s.kpis.length > 0) {
      const numKpis = Math.min(s.kpis.length, 6);
      const totalW = 12.33;
      const gap = 0.15;
      const cardW = (totalW - (numKpis - 1) * gap) / numKpis;

      s.kpis.slice(0, 6).forEach((kpi, idx) => {
        const cardX = 0.5 + idx * (cardW + gap);

        // Card Container
        slide.addShape(pptx.ShapeType.roundRect, {
          x: cardX, y: 1.18, w: cardW, h: 0.75,
          rectRadius: 0.05,
          fill: { color: 'FFFFFF' },
          line: { color: 'E2E8F0', width: 1 }
        });

        // Label
        slide.addText(String(kpi.label || '').toUpperCase(), {
          x: cardX + 0.08, y: 1.22, w: cardW - 0.16, h: 0.16,
          fontSize: 7, color: '64748B', bold: true, fontFace: 'Calibri'
        });

        // Value
        const valColor =
          kpi.sentiment === 'positive' ? '059669' :
          kpi.sentiment === 'negative' ? 'DC2626' : '1E293B';

        slide.addText(String(kpi.value || ''), {
          x: cardX + 0.08, y: 1.38, w: cardW - 0.16, h: 0.28,
          fontSize: 13, color: valColor, bold: true, fontFace: 'Calibri'
        });

        // Subtext
        if (kpi.sub) {
          slide.addText(String(kpi.sub), {
            x: cardX + 0.08, y: 1.66, w: cardW - 0.16, h: 0.16,
            fontSize: 7, color: '94A3B8', fontFace: 'Calibri'
          });
        }
      });
    }

    // ─── 3. 2-Column Structured Content Cards (y: 2.05 to 6.80) ───────────
    const colY = 2.05;
    const colH = 4.75;
    const colW = 6.02;

    // Left Column Card
    slide.addShape(pptx.ShapeType.roundRect, {
      x: 0.5, y: colY, w: colW, h: colH,
      rectRadius: 0.06,
      fill: { color: 'FFFFFF' },
      line: { color: 'CBD5E1', width: 1 }
    });

    // Left Column Header Strip
    slide.addShape(pptx.ShapeType.roundRect, {
      x: 0.5, y: colY, w: colW, h: 0.38,
      rectRadius: 0.06,
      fill: { color: 'F1F5F9' },
      line: { color: 'CBD5E1', width: 1 }
    });

    const leftTitle = s.leftSection?.title || 'Key Strategic Observations';
    slide.addText(leftTitle.toUpperCase(), {
      x: 0.7, y: colY + 0.08, w: 5.6, h: 0.22,
      fontSize: 9.5, color: '1E3A5F', bold: true, fontFace: 'Calibri'
    });

    // Left Column Bullets
    const leftItems = s.leftSection?.items || s.bullets?.slice(0, 4) || [];
    const leftBulletText = leftItems.map(item => ({
      text: item.replace(/\*\*/g, '').replace(/^[🔴🟠🟡🟢✅⚠️📌]\s*/, ''),
      options: {
        bullet: { type: 'bullet', code: '2022' },
        fontSize: 10.5,
        color: '334155',
        paraSpaceAfter: 8,
        fontFace: 'Calibri'
      }
    }));

    if (leftBulletText.length > 0) {
      slide.addText(leftBulletText, {
        x: 0.7, y: colY + 0.48, w: 5.62, h: 4.15,
        valign: 'top'
      });
    }

    // Right Column Card
    const rightX = 6.81;
    slide.addShape(pptx.ShapeType.roundRect, {
      x: rightX, y: colY, w: colW, h: colH,
      rectRadius: 0.06,
      fill: { color: 'FFFFFF' },
      line: { color: 'CBD5E1', width: 1 }
    });

    // Right Column Header Strip
    slide.addShape(pptx.ShapeType.roundRect, {
      x: rightX, y: colY, w: colW, h: 0.38,
      rectRadius: 0.06,
      fill: { color: 'F1F5F9' },
      line: { color: 'CBD5E1', width: 1 }
    });

    const rightTitle = s.rightSection?.title || 'Impact Analysis & Strategic Focus';
    slide.addText(rightTitle.toUpperCase(), {
      x: rightX + 0.2, y: colY + 0.08, w: 5.6, h: 0.22,
      fontSize: 9.5, color: '1E3A5F', bold: true, fontFace: 'Calibri'
    });

    // Right Column Bullets
    const rightItems = s.rightSection?.items || s.bullets?.slice(4) || [];
    const rightBulletText = rightItems.map(item => ({
      text: item.replace(/\*\*/g, '').replace(/^[🔴🟠🟡🟢✅⚠️📌]\s*/, ''),
      options: {
        bullet: { type: 'bullet', code: '2022' },
        fontSize: 10.5,
        color: '334155',
        paraSpaceAfter: 8,
        fontFace: 'Calibri'
      }
    }));

    if (rightBulletText.length > 0) {
      slide.addText(rightBulletText, {
        x: rightX + 0.2, y: colY + 0.48, w: 5.62, h: 4.15,
        valign: 'top'
      });
    }

    // ─── 4. Footer Governance Bar (y: 6.95 to 7.30) ────────────────────────
    slide.addShape(pptx.ShapeType.line, {
      x: 0.5, y: 6.95, w: 12.33, h: 0,
      line: { color: 'E2E8F0', width: 1 }
    });

    slide.addText('Confidential · Crystal Ball Analytics Enterprise Intelligence Platform · Real-time Executive Insights', {
      x: 0.5, y: 7.02, w: 8.5, h: 0.28,
      fontSize: 8, color: '94A3B8', fontFace: 'Calibri'
    });

    slide.addText(`Slide ${s.id} of 5 · ${new Date().toLocaleDateString()}`, {
      x: 9.2, y: 7.02, w: 3.6, h: 0.28,
      fontSize: 8, color: '94A3B8', align: 'right', fontFace: 'Calibri'
    });
  }

  const dateStr = new Date().toISOString().slice(0, 10);
  const fileName = `Crystal_Ball_Executive_Briefing_${dateStr}.pptx`;
  await pptx.writeFile({ fileName });
  return fileName;
}
